apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-dashboard
# namePrefix: prod-
# nameSuffix: "-001"
commonAnnotations:
  oncallPager: 800-555-1212
commonLabels:
  app: traefik-dashboard

configMapGenerator:
- name: traefik-tls
  literals:
  - name=traefik-tls

# replacements:
#   - name: DOMAIN-TLS
#     objref:
#        kind: IngressRoute
#        name: treafik-dashboard
#     fieldref:
#       fieldpath: spec.routes.0.tls.secretName
      



resources:
 - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: traefik.abe.zone
      - op: replace
        path: /spec/secretName
        value: traefik-tls
    target:
      kind: Certificate

  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value:  Host(`traefik.abe.zone`)
      - op: replace 
        path: /spec/tls/secretName
        value: traefik-tls
    target: 
      kind: IngressRoute