apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: p
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      team: sm-team
  resources:
    requests:
      memory: 400Mi