apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
 type: NodePort
 ports:
  - port: 9090
    targetPort: 9090
    nodePort: 33000
    protocol: TCP
 selector:
     app: prometheus