apiVersion: apps/v1
kind: Deployment
metadata:
  name: "pink91"
spec:
  selector:
    matchLabels:
      app: k3s-pink
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: k3s-pink
    spec:
      containers:
        - name: k3s-pink
          image: concan/pink:latest 
          resources:
            limits:
              cpu: "10"
              memory: "2G"
            requests:
              cpu: "8"
              memory: "1G"
              
      restartPolicy: Never
