apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-compress
spec:
  compress: 
    minResponseBodyBytes: 1024

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: known-ips
spec:
  ipWhiteList:
    sourceRange:
    - 127.0.0.1/32
    - 10.42.0.0/16
    - 10.43.0.0/16
--- 
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain
spec:
  chain:
    middlewares:
    - name: traefik-middleware-compress
    - name: known-ips
    # - name: auth-users