apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
namePrefix: dev-
nameSuffix: "-001"
commonAnnotations:
  oncallPager: 800-555-1212
commonLabels:
  app: cert-manager
images:
  - name: h1 
    newName: h2
    newTag: lastest


resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml