apiVersion: apps/v1
kind: Deployment
metadata:
  name: erigon-deployment
spec:
  selector:
    matchLabels:
      app: erigon
  replicas: 1 # 告知 Deployment 运行 1 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: erigon
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0

      containers:
      - name: erigon
        image: thorax/erigon:v2.57.3
        command: ["/usr/local/bin/erigon"]
        args: ["--chain","mainnet","--datadir","/data/ethereum","--http", "--http.api=engine,eth,web3,net","--authrpc.addr=0.0.0.0","--authrpc.vhosts='*'","--authrpc.port=8551","--prune=htc","--prune.r.before=11052984"]
        ports:
        - containerPort: 8551
        resources:
          requests:
            cpu: 1000m
            memory: 2000Mi
          limits:
            cpu: 2000m
            memory: 4000Mi
        volumeMounts:
          - name: config 
            mountPath: /data/ethereum
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: erigon-pvc