apiVersion: v1
kind: Service
metadata:
  name: ergion-service
  labels:
     app: erigion
spec:
  type: NodePort
  ports:
  - port: 8551
    targetPort: 8551
    protocol: TCP
  selector:
     app: erigon