- name: Install master
  hosts: master
  tasks:
    - name: echo "hello world !!!"
      command: echo "hello world"
      when:
      register: result
    - name: debug
      debug:
        msg: ""
        
- name: Install node
  hosts: node
  tasks:
    - name: echo "hello world"
      command: 

