- name: Install master
  hosts: master
  tasks:
    - name: Install k3s master 
      shell: curl -sfL https://get.k3s.io | sh -
      ignore_errors: true
    - name: query k3s keys
      command: cat /var/lib/rancher/k3s/server/node-token
      register: token_result
    - name: show k3s keys
      debug: "{{ token_result.stdout }}"