listen: :555

tls:
  cert: /app/tls.crt
  key: /app/tls.key

auth:
  type: password
  password: Se7RAuFZ8Lzg 

masquerade: 
  type: proxy
  proxy:
    url: https://news.ycombinator.com/ 
    rewriteHost: true