apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: hysteria2-ingress
  namespace: hysteria2
spec:
  entryPoints:
  - webudp
  routes:
  - services:
    - name: hysteria2-service
      port: 49155