apiVersion: v1
kind: Service
metadata:
  name: hysteria2-service
  namespace: hysteria2
  labels:
     app: hysteria2
spec:
  type: NodePort
  ports:
  - port: 49155
    nodePort: 31888
    targetPort: 31888
    protocol: UDP
  selector:
     app: hysteria2