apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
     app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        imagePullPolicy: IfNotPresent
        name: node-exporter
        command: ["/bin/node_exporter","--collector.processes","--collector.systemd"]
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: scrape
          volumeMounts:
            - mountPath: /var/run/dbus
              name: system-dbus-socket
              readOnly: true
      volumes:
      - hostPath:
          path: /var/run/dbus
        name: system-dbus-socket
      hostNetwork: true
      hostPID: true