apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-node-exporter
  labels:
    team: sm-team
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: scrape