apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  labels:
   app: node-exporter 
spec:
 ports:
  - port: 9100
    targetPort: 9100
    protocol: TCP
    name: scrape
 selector:
     app: node-exporter