apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
generatorOptions:
    disableNameSuffixHash: true
    
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
  - pv.yaml