apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray
spec:
  selector:
    matchLabels:
      app: xray
  replicas: 1 
  template:
    metadata:
      labels:
        app: xray
    spec:
      containers:
      - name: xray
        image: teddysun/xray:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30666
        livenessProbe:
          tcpSocket: 
            port: 30666
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: 5m
            memory: 5Mi
          limits:
            cpu: 120m
            memory: 150Mi
        volumeMounts: 
             - name: config
               mountPath: /etc/xray
        
      volumes:
        - name: config 
          configMap: 
             name: xray-config
      restartPolicy: Always
        