apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: xray
configMapGenerator:
- name: xray-config
  files:
    - config.json
generatorOptions:
    disableNameSuffixHash: true
    
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml